function report = add_hash5_before_final_counter(folder_path, dry_run, recursive)
%ADD_HASH5_BEFORE_FINAL_COUNTER Insert "_#5" before the final filename counter.
%
%   add_hash5_before_final_counter()
%       Scans the current folder in preview mode.
%
%   add_hash5_before_final_counter(folder_path)
%       Scans folder_path in preview mode.
%
%   add_hash5_before_final_counter(folder_path, dry_run)
%       dry_run = true  : preview only (default)
%       dry_run = false : actually rename files
%
%   add_hash5_before_final_counter(folder_path, dry_run, recursive)
%       recursive = true also scans subfolders (default: false).
%
% Examples:
%   Curva_Polarizacion_Asc_33s_2x_#7.DTA
%       -> Curva_Polarizacion_Asc_33s_2x_#5_#7.DTA
%
%   Curva_Polarizacion_Dsc_33s_2x_#4_#7.DTA
%       -> unchanged
%
% Only filenames ending in exactly one trailing "_#number.DTA" are changed.
% Files already ending in "_#number_#number.DTA" are left unchanged.
% The contents of the .DTA files are not modified.

  if nargin < 1 || isempty(folder_path)
    folder_path = pwd;
  endif

  if nargin < 2 || isempty(dry_run)
    dry_run = true;
  endif

  if nargin < 3 || isempty(recursive)
    recursive = false;
  endif

  if !ischar(folder_path)
    error('folder_path must be a character vector.');
  endif

  if exist(folder_path, 'dir') != 7
    error('Folder does not exist: %s', folder_path);
  endif

  files = collect_dta_files(folder_path, recursive);

  old_paths = {};
  new_paths = {};
  old_names = {};
  new_names = {};

  for k = 1:numel(files)
    old_name = files(k).name;

    % Skip files already ending with two counters, e.g. _#4_#7.DTA.
    already_has_two_counters = !isempty( ...
      regexpi(old_name, '_#[0-9]+_#[0-9]+\.DTA$', 'once'));

    % Match a single final counter, e.g. _#7.DTA.
    single_final_counter = !isempty( ...
      regexpi(old_name, '_#[0-9]+\.DTA$', 'once'));

    if single_final_counter && !already_has_two_counters
      % Insert "_#5" immediately before the final counter.
      new_name = regexprep( ...
        old_name, ...
        '(_#[0-9]+\.[Dd][Tt][Aa])$', ...
        '_#5$1');

      old_path = fullfile(files(k).folder, old_name);
      new_path = fullfile(files(k).folder, new_name);

      old_paths{end + 1} = old_path;
      new_paths{end + 1} = new_path;
      old_names{end + 1} = old_name;
      new_names{end + 1} = new_name;
    endif
  endfor

  total_matches = numel(old_paths);
  renamed = 0;
  skipped = 0;
  failed = 0;

  fprintf('\nFolder: %s\n', folder_path);
  fprintf('Recursive: %s\n', logical_text(recursive));
  fprintf('Mode: %s\n\n', ternary(dry_run, 'PREVIEW ONLY', 'RENAME FILES'));

  if total_matches == 0
    fprintf('No matching .DTA filenames were found.\n');
    report = make_report(total_matches, renamed, skipped, failed, dry_run);
    return;
  endif

  % Detect duplicate destination names generated by this batch.
  duplicate_target = false(1, total_matches);

  for i = 1:total_matches
    for j = i + 1:total_matches
      if strcmpi(new_paths{i}, new_paths{j})
        duplicate_target(i) = true;
        duplicate_target(j) = true;
      endif
    endfor
  endfor

  for k = 1:total_matches
    fprintf('%4d. %s\n      -> %s\n', ...
      k, old_names{k}, new_names{k});

    if duplicate_target(k)
      fprintf('      SKIPPED: more than one source would create this target.\n');
      skipped = skipped + 1;
      continue;
    endif

    % Never overwrite an existing file.
    if exist(new_paths{k}, 'file') == 2
      fprintf('      SKIPPED: destination already exists.\n');
      skipped = skipped + 1;
      continue;
    endif

    if dry_run
      continue;
    endif

    [ok, message] = movefile(old_paths{k}, new_paths{k});

    if ok
      renamed = renamed + 1;
    else
      fprintf('      FAILED: %s\n', message);
      failed = failed + 1;
    endif
  endfor

  fprintf('\nSummary\n');
  fprintf('  Matching filenames: %d\n', total_matches);

  if dry_run
    fprintf('  Files renamed:      0 (preview mode)\n');
    fprintf('  Files skipped:      %d\n', skipped);
    fprintf('\nRun again with dry_run = false to apply the changes.\n');
  else
    fprintf('  Files renamed:      %d\n', renamed);
    fprintf('  Files skipped:      %d\n', skipped);
    fprintf('  Failures:           %d\n', failed);
  endif

  report = make_report(total_matches, renamed, skipped, failed, dry_run);
endfunction


function files = collect_dta_files(folder_path, recursive)
  entries = dir(folder_path);
  files = struct('name', {}, 'folder', {});

  for k = 1:numel(entries)
    name = entries(k).name;

    if entries(k).isdir
      if recursive && !strcmp(name, '.') && !strcmp(name, '..')
        subfolder = fullfile(folder_path, name);
        subfiles = collect_dta_files(subfolder, true);
        files = [files, subfiles];
      endif
    elseif !isempty(regexpi(name, '\.DTA$', 'once'))
      item.name = name;
      item.folder = folder_path;
      files(end + 1) = item;
    endif
  endfor
endfunction


function text = logical_text(value)
  if value
    text = 'yes';
  else
    text = 'no';
  endif
endfunction


function result = ternary(condition, true_value, false_value)
  if condition
    result = true_value;
  else
    result = false_value;
  endif
endfunction


function report = make_report(matches, renamed, skipped, failed, dry_run)
  report = struct( ...
    'matching_filenames', matches, ...
    'renamed', renamed, ...
    'skipped', skipped, ...
    'failed', failed, ...
    'dry_run', logical(dry_run));
endfunction
